spring:

  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: jardinahora

  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto=: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        #default_schema: cadastro,sistema-embarcado,viagem

    security:
      oauth2:
        client:
          registration:
            github:
              client-id: ${GITHUB_CLIENT_ID}
              client-secret: ${GITHUB_CLIENT_SECRET}
              scope: user:email, read:user
            google:
              client-id: ${GOOGLE_CLIENT_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}
              scope: email, profile

frontend:
  url: ${FRONTEND_URL}
